services:
  web:
    build : .
    ports:
      - 8900:80
    volumes:
      - ./../app:/var/www/html
      - .env:/var/www/html/.env
    container_name: web
  mysql:
    image: mysql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./datos.sql:/docker-entrypoint-initdb.d/datos.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
    ports:
      - 33306:3306
    container_name: mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8200:80
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
    container_name: phpmyadmin
